[features]
seeds = false
[programs.devnet]
mint_nft = "2PtNMeZuzXzgabHwG41EeTJL16d5GgTZgNbXaZ5VxZYe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/moderate/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
